version: "3"

#GOOGLE_CLIENT_ID: "cneorfn034"

services:
  reverse-proxy:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker --entryPoints.web.address=:80 --entryPoints.web.forwardedHeaders.insecure
    networks:
      - executeit
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis
    networks:
      - executeit

  app:
    build:
      context: .
    ports:
      - "5000"
    restart: always
    volumes:
      - ./:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - executeit
    command: >
      sh -c "yarn dev"
    environment:
      - NODE_ENV=dev
      - PORT=5000
      - DOCKER_SOCKET=/var/run/docker.sock
      - USER_SERVER_URL=rooms.localhost
      - USER_SERVER_IMAGE=user-image-1
      - USER_SERVER_CPU_LIMIT=10
      - USER_SERVER_MEM_LIMIT=256000
      - USER_SERVER_NETWORK=executeit
      - MONGO_HOST=mongo
      - MONGO_DB_NAME=executeit
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=/auth/google/callback
      - JWT_SECRET=gocoronago
      - OT_SERVER_URL=http://ot-server/api/rest
      - FRONTEND_REDIRECT_URL=http://localhost:3000/callback
      - AUTH_SERVER_URL=http://localhost/auth
      - USER_DATA_BASE_PATH=/home/execute-it-user-data # without trailing /
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AUTO_CULL_QUEUE=auto-cull-queue
      - AUTO_SAVE_QUEUE=auto-save-queue

    labels:
      - "traefik.http.routers.app.rule=Host(`localhost`)"
  mongo:
    image: mongo
    restart: always
    networks:
      - executeit
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - executeit
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  
  ot-server:
    image: convergencelabs/convergence-omnibus
    networks:
      - executeit
    ports:
      - "80"
    labels:
      - "traefik.http.routers.ot-server.rule=Host(`ot.localhost`)"

  auto-save-cull:
    image: auto-save-cull
    environment:
      CONVERGENCE_API_KEY: "UGCvXZUKuYGhajyaA4cWGtRwDJIsiPpAzJ3uMsvZ4D73kW9DAGyh2rMMwcbF5Gbt"
      OT_SERVER_URL: https://ot.executeit.ml/api
      USER_DATA_BASE_PATH: "/worker/data" # Path inside container
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      AUTOSAVE_INTERVAL: 4 # In secs
      AUTOCULL_INTERVAL: 10 # In secs (60*5)
      DOCKER_SOCKET: "/var/run/docker.sock"
    command: node app
    networks:
      - executeit
    volumes:
      - /home/execute-it-user-data:/worker/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  executeit:
    external:
      name: executeit